### ISSUE TITLE
mongodb-seed should wait for templateprocessor to finish

### ISSUE THREAD

**Issue by micskeiz** [Prometheus-X-association/ptx-docker#8]
Currently, mongoddb-seed only waits for templateprocessor to start, but it should wait until it is exited.

Something similar could be added to the compose file for mongodb-seed

```
    depends_on:
      mongodb:
        condition: service_started
      template-preprocessor:
        condition: service_completed_successfully
```
